#팀 클라우드 oauth yml파일
spring:
  security:
    oauth2:
      client:
        registration:
          kakao:
            client-id: 3e644b4cfe7ccd04e6be5b922c76c3ef
            client-secret: TQQa3F6vRpYjnpT6e5TyRXPhXheIk2Jt
            client-name: kakao
            client-authentication-method: POST
            authorization-grant-type: authorization_code
            redirect-uri: http://${VM_DOMAIN}/login/oauth2/code/kakao
            scope:
              - profile_image
              - profile_nickname
              - account_email
          google:
            client-id: 557225271854-j5v1hrh4iqkc7bbfidqrcj74uvfbbjca.apps.googleusercontent.com
            client-secret: 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
            scope: profile, email
          naver:
            client-id: WdaJ_Or0QQP0Ct0vWPIi
            client-secret: fdFY6qWJdv
            scope: name, email, profile_image
            client-name: naver
            authorization-grant-type: authorization_code
            redirect-uri: http://${VM_DOMAIN}/login/oauth2/code/naver
        provider:
          kakao:
            authorization-uri: http://kauth.kakao.com/oauth/authorize
            token-uri: http://kauth.kakao.com/oauth/token
            user-info-uri: http://kapi.kakao.com/v2/user/me
            user-name-attribute: id
          naver:
            authorization-uri: http://nid.naver.com/oauth2.0/authorize
            token-uri: http://nid.naver.com/oauth2.0/token
            user-info-uri: http://openapi.naver.com/v1/nid/me
            user-name-attribute: response
