name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    env:  # 환경 변수 정의
      AZURE_VM_IP: ${{ secrets.AZURE_VM_IP }}  # Azure VM IP 환경 변수
      MYSQL_HOST: ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT : ${{ secrets.MYSQL_PORT }}
      MYSQL_USER : ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD : ${{ secrets.MYSQL_PASSWORD }}
      K_CLIIENT_ID : ${{ secrets.K_CLIIENT_ID }}
      K_CLIIENT_SECRET : ${{ secrets.K_CLIIENT_SECRET }}
      N_CLIENT_ID : ${{ secrets.N_CLIENT_ID }}
      N_CLIENT_SECRET : ${{ secrets.N_CLIENT_SECRET }}
      K_AUTH : ${{ secrets.K_AUTH }}
      K_AUTH_TOKEN : ${{ secrets.K_AUTH_TOKEN }}
      N_AUTH : ${{ secrets.N_AUTH }}
      N_AUTH_TOKEN : ${{ secrets.N_AUTH_TOKEN }}
    
    steps:
      - uses : actions/checkout@v3

      - uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution : 'corretto'

      - name : Grant execute permission for gradlew
        run : chmod +x NotificationSite/gradlew

      - name : init gradlew
        run : NotificationSite/gradlew init

      - name: Build JAR
        run: NotificationSite/gradlew build

      - name: Upload JAR to Azure VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.AZURE_VM_IP }}
          username: azureuser
          key: ${{ secrets.AZURE_SSH_PRIVATE_KEY }}
          source: NotificationSite/build/libs/NotificationSite-0.0.8.jar
          target: /home/azureuser/NoticeSite